routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/jenis-tabungan', 'JenisTabunganController' );
Route::resource('/member', 'MemberController' );
Route::resource('/transaksi', 'TransaksiController');
Route::resource('/tabungan', 'TabunganController');
Route::get('/tabungan/{id}/transaksi', 'TransaksiController@create')->name('tabungan.transaksi.create');
Route::post('/tabungan/{id}/transaksi', 'TransaksiController@store')->name('tabungan.transaksi.store');

app/Tabungan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tabungan extends Model
{
    protected $table = "tabungan";
    protected $fillable = ["no_rekening","saldo_awal","saldo","tanggal_registrasi","member_id", "jenis_tabungan_id"];

    public function member()
    {
        return $this->belongsTo('App\Member', 'member_id');
    }

    public function jenistabungan()
    {
        return $this->belongsTo('App\jenisTabungan', 'jenis_tabungan_id');
    }

    /**
     * Get all of the transaksi for the Tabungan
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function transaksi()
    {
        return $this->hasMany(Transaksi::class)->orderBy('tanggal_transaksi', 'ASC');
    }

}

app/Http/Controllers/TabunganController.php
<?php

namespace App\Http\Controllers;

use App\jenisTabungan;
use App\Member;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use App\Tabungan;
use App\Transaksi;

class TabunganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tabungan = Tabungan::all();
        $data['active_menu'] = 'tabungan';
        return view('tabungan.index', compact('tabungan','data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $member = Member::all();
        $jenis_tabungan = jenisTabungan::all();
        $data['active_menu'] = 'tabungan';
        return view('tabungan.create', compact('member','jenis_tabungan','data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
            'no_rekening' => 'required',
            'saldo_awal' => 'required',
            'tanggal_registrasi' => 'required',
            'member_id' => 'required',
            'jenis_tabungan_id' => 'required',
            ],
            [
            'no_rekening.required' => 'No_Rekening harus diisi',
            'saldo_awal.required'  => 'Saldo Awal harus diisi',
            'tanggal_registrasi.required'  => 'Tanggal Registrasi harus diisi',
            'member_id' => 'Member Harus diisi',
            'jenis_tabungan_id' => 'Jenis tabungan harus diisi'
            ]
        );

        $tabungan = new Tabungan;
        $tabungan->no_rekening = $request->no_rekening;
        $tabungan->saldo_awal = $request->saldo_awal;
        $tabungan->saldo = $request->saldo_awal;
        $tabungan->tanggal_registrasi = $request->tanggal_registrasi;
        $tabungan->member_id = $request->member_id;
        $tabungan->jenis_tabungan_id = $request->jenis_tabungan_id;


        $tabungan->save();

        $transaksi = [
            'tanggal_transaksi' => now()->format('Y-m-d'),
            'kode_transaksi' => uniqid(),
            'tipe' => 0,
            'jumlah' => $request->saldo_awal,
            'tabungan_id' => $tabungan->id
        ];
        Transaksi::create($transaksi);

        return redirect('/tabungan')->with('success', 'Data tabungan berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['data'] = Tabungan::with(['transaksi', 'member', 'jenistabungan'])->findOrFail($id);
        $data['active_menu'] = 'tabungan';

        return view ('tabungan.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['data'] = Tabungan::find($id);
        $data['active_menu'] = 'tabungan';
        $data['jenis'] = jenisTabungan::all();
        return view ('tabungan.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'no_rekening' => 'required|numeric',
            'jenis_tabungan_id' => 'required||numeric'
        ]);
        Tabungan::where('id', $id)->update([
            'no_kredit' => $request->no_kredit,
            'jenis_tabungan_id' => $request->jenis_tabungan_id,
        ]);
        return redirect('/tabungan')->with('success', 'Data tabungan berhasil diperbaharui!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tabungan::where('id', $id)->delete();
        Transaksi::where('tabungan_id', $id)->delete();
        return redirect('/tabungan')->with('success', 'Data tabungan berhasil dihapus!');
    }
}

resources/views/tabungan/create.blade.php
@extends('template.master')

@section('title', 'Tabungan')

@section('card-title')
    <h3 class="card-title">Buat Tabungan</h3>
@endsection

@push('style')
    <link rel="stylesheet" type="text/css" href="{{asset('https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" type="text/css" href="{{asset('datepicker/css/datepicker.css')}}"/>
@endpush

@section('content')
    <form action="/tabungan" method="POST" id="form">
        @csrf
        <div class="card-body">

            <div class="form-group">
                <label>Nama member</label>
                <select name="member_id" id="" class="form-control">
                    @forelse ($member as $key => $item)
                        <option value="{{$item->id}}">{{$item->nama}}</option>
                    @empty
                        <option value="">--Tidak ada Data Member--</option>
                    @endforelse
                </select>
                @error('nama')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>


            <div class="form-group">
                <label>Jenis Tabungan</label>
                <select name="jenis_tabungan_id" id="" class="form-control">
                    @forelse ($jenis_tabungan as $key => $item)
                        <option value="{{$item->id}}">{{$item->nama}}</option>
                    @empty
                        <option value="">---Tidak ada Data Jenis Tabungan--</option>
                    @endforelse
                </select>
                @error('jenis_tabungan')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>


            <div class="form-group">
                <label for="no_rekening">No. Rekening</label>
                <input type="number" class="form-control" name="no_rekening" id="no-rekening" placeholder="Masukkan Nomor Rekening" value="{{ old('no_rekening', '') }}"/>
                @error('no_rekening')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>


            <div class="form-group">
                <label for="saldo_awal">Saldo Awal</label>
                <input type="text" class="form-control" name="saldo_awal" id="saldo-awal" placeholder="Masukkan Saldo Awal" value="{{ old('saldo_awal', '') }}"/>
                @error('saldo_awal')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>


            <div class="form-group">
                <label for="tanggal_registrasi">Tanggal Registrasi</label>
                <div class="form-group">
                    <input type="text"  name="tanggal_registrasi"  class="form-control datepicker"  required>
                </div>
                @error('tanggal_registrasi')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Buat Tabungan</button>
        </div>
    </form>

@endsection

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{{asset('datepicker/js/bootstrap-datepicker.js')}}"></script>
    <script type="text/javascript">
        $(function() {
            $(".datepicker").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayHighlight: true,
            });
        });
    </script>
@endpush

resources/views/tabungan/edit.blade.php
@extends('template.master')

@section('title', 'Tabungan')

@section('card-title')
    <h3 class="card-title">Edit Tabungan</h3>
@endsection

@push('style')
    <link rel="stylesheet" type="text/css" href="{{asset('https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" type="text/css" href="{{asset('datepicker/css/datepicker.css')}}"/>
@endpush

@section('content')
    <form action="{{ route('tabungan.update', $data['data']->id) }}" method="POST" id="form">
        @csrf
        @method('PUT')
        <div class="card-body">

            <div class="form-group">
                <label>Jenis Tabungan</label>
                <select name="jenis_tabungan_id" id="" class="form-control">
                    @forelse ($data['jenis'] as $key => $item)
                        <option value="{{$item->id}}" {{ $item->id == $data['data']->jenis_tabungan_id ? 'selected' : '' }}>{{$item->nama}}</option>
                    @empty
                        <option value="">---Tidak ada Data Jenis Tabungan--</option>
                    @endforelse
                </select>
                @error('jenis_tabungan')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>


            <div class="form-group">
                <label for="no_rekening">No. Rekening</label>
                <input type="number" class="form-control" name="no_rekening" id="no-rekening" placeholder="Masukkan Nomor Rekening" value="{{ $data['data']->no_rekening }}"/>
                @error('no_rekening')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update Tabungan</button>
        </div>
    </form>

@endsection

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{{asset('datepicker/js/bootstrap-datepicker.js')}}"></script>
    <script type="text/javascript">
        $(function() {
            $(".datepicker").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayHighlight: true,
            });
        });
    </script>
@endpush

resources/views/tabungan/index.blade.php
@extends('template.master')

@section('title', 'Tabungan')

@section('card-title')
    <h3 class="card-title">Daftar Tabungan</h3>
@endsection

@push('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.5/datatables.min.css"/>
@endpush

<!-- library datepicker-->
@push('style')

@endpush

@section('content')

    @if(session('success'))
        <div class="alert alert-success my-2 mx-2">
            {{ session('success') }}
        </div>
    @endif

    <div>
        <a class="btn btn-primary ml-2 my-2" href="/tabungan/create">Buat Tabungan</a>
    </div>

    <div class="mx-2">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>No. Rekening</th>
                    <th>Saldo</th>
                    <th>Tanggal Registrasi</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

            @forelse ($tabungan as $key => $item)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $item->no_rekening}}</td>
                    <td>Rp {{ number_format($item->saldo, 0, ',', '.') }}</td>
                    <td>{{ $item->tanggal_registrasi}}</td>

                    <td>
                        {{-- <a class="btn btn-info btn-sm" href="/transaksi/create">Tambah Transaksi</a> --}}
                        <form action="{{ route('tabungan.destroy', $item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a class="btn btn-info btn-sm" href="/tabungan/{{ $item->id }}">Detail</a>
                            <a class="btn btn-warning btn-sm" href="/tabungan/{{ $item->id }}/edit">Edit</a>
                            <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                        </form>
                    </td>

                </tr>
            @empty
                <h2>Tidak ada Daftar Tabungan yang ditemukan</h2>
            @endforelse

            </tbody>

            <tfoot>
                <tr>
                    <th>No</th>
                    <th>No. Rekening</th>
                    <th>Saldo</th>
                    <th>Tanggal Registrasi</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>


@endsection

@push('scripts')
    <script src="{{ asset('/adminlte/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{ asset('/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
    <script>
        $(function () {
            $("#example1").DataTable();
        });
    </script>
@endpush

resources/views/tabungan/show.blade.php
@extends('template.master')

@section('title', 'Tabungan')

@section('card-title')
    <h3 class="card-title">Detail Tabungan</h3>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-2">No Rekening</div>
        <div class="col-sm">{{ $data['data']->no_rekening }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Member</div>
        <div class="col-sm">{{ $data['data']->member->nama }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Jenis Tabungan</div>
        <div class="col-sm">{{ $data['data']->jenistabungan->nama }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Tanggal Registrasi</div>
        <div class="col-sm">{{ $data['data']->tanggal_registrasi }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Saldo Awal</div>
        <div class="col-sm">Rp{{ number_format($data['data']->saldo_awal) }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Saldo</div>
        <div class="col-sm">Rp{{ number_format($data['data']->saldo) }}</div>
    </div>
    <div class="d-flex justify-content-between">
        <h3>Transaksi</h3>
        <a href="{{ route('tabungan.transaksi.create', $data['data']->id) }}" class="btn btn-success">Tambah Transaksi</a>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>No</th>
                <th>Tanggal Transaksi</th>
                <th>Kode Transaksi</th>
                <th>Tipe</th>
                <th>Jumlah</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data['data']->transaksi as $key => $value)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $value->tanggal_transaksi }}</td>
                    <td>{{ $value->kode_transaksi }}</td>
                    <td>{{ $value->tipe ? 'Pengurangan' : "Penambahan" }}</td>
                    <td>Rp{{ number_format($value->jumlah) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

@endsection