routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/jenis-tabungan', 'JenisTabunganController' );
Route::resource('/member', 'MemberController' );
Route::resource('/transaksi', 'TransaksiController');
Route::resource('/tabungan', 'TabunganController');
Route::get('/tabungan/{id}/transaksi', 'TransaksiController@create')->name('tabungan.transaksi.create');
Route::post('/tabungan/{id}/transaksi', 'TransaksiController@store')->name('tabungan.transaksi.store');

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    protected $table = 'member';

    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tabungan()
    {
        return $this->hasMany('App\Tabungan');
    }

}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Member;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class MemberController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['data'] = Member::all();
        $data['active_menu'] = 'member';
        return view('member.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['active_menu'] = 'member';
        return view('member.create', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kode' => 'required',
            'nama' => 'required',
            'jenis_kelamin' => 'required||numeric',
            'email' => 'required|email',
            'password' => 'required|min:6',
        ]);
        $user = [
            'name' => $request->nama,
            'email' => $request->email,
            'email_verified_at' => DB::raw('NOW()'),
            'password' => Hash::make($request->password),
            'level' => 'anggota',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
        ];
        $newUser = User::create($user);
        $member = [
            'nama' => $request->nama,
            'jenis_kelamin' => $request->jenis_kelamin,
            'alamat' => $request->alamat,
            'kode' => $request->kode,
            'user_id' => $newUser->id
        ];
        Member::create($member);
        return redirect('/member')->with('success', 'Data member berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['member'] = Member::with('user')->findOrFail($id);
        $data['active_menu'] = 'member';
        return view('member.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['member'] = Member::with('user')->findOrFail($id);
        $data['active_menu'] = 'member';
        return view('member.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $member = Member::findOrFail($id);
        $request->validate([
            'kode' => 'required',
            'nama' => 'required',
            'jenis_kelamin' => 'required||numeric',
            'email' => 'required|email',
            'password' => 'nullable|min:6',
        ]);
        $user = [
            'name' => $request->nama,
            'email' => $request->email,
            'level' => 'anggota',
            'updated_at' => DB::raw('NOW()'),
        ];
        if($request->has('password') && $request->password != ''){
            $user['password'] = Hash::make($request->password);
        }
        $newUser = User::where('id',$member->user_id)->update($user);
        $member = [
            'nama' => $request->nama,
            'jenis_kelamin' => $request->jenis_kelamin,
            'alamat' => $request->alamat,
            'kode' => $request->kode
        ];
        Member::where('id', $id)->update($member);
        return redirect('/member')->with('success', 'Data member berhasil diperbaharui!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $member = Member::findOrFail($id);
        User::where('id', $member->user_id)->delete();
        $member->delete();
        return redirect('/member')->with('success', "Data member berhasil dihapus!");
    }
}

resources/views/member/create.blade.php
@extends('template.master')

@section('title', 'Member')

@section('card-title')
    <h3 class="card-title">Tambah Member</h3>
@endsection

@section('content')

    @if(session('error'))
        <div class="alert alert-danger my-2 mx-2">
            {{ session('error') }}
        </div>
    @endif

    <form action="{{ route('member.store') }}" method="post">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="kode">Kode</label>
                <input type="text" class="form-control" id="kode" placeholder="Masukan kode" name="kode">
                @error('kode')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama">Nama</label>
                <input type="text" class="form-control" id="nama" placeholder="Masukan nama" name="nama">
                @error('nama')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama">Jenis Kelamin</label> <br>
                <input type="radio" name="jenis_kelamin" value="0" checked> Perempuan
                <input type="radio" name="jenis_kelamin" value="1"> Laki Laki
                @error('jenis_kelamin')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="alamat">Alamat</label>
                <textarea class="form-control" rows="3" placeholder="Masukan alamat" name="alamat"></textarea>
                @error('alamat')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Masukan email" name="email">
                @error('email')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" placeholder="Masukan password" name="password">
                @error('password')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" name="simpan" class="btn btn-info">Simpan</button>
        </div>
    </form>


@endsection

resources/views/member/edit.blade.php
@extends('template.master')

@section('title', 'Member')

@section('card-title')
    <h3 class="card-title">Edit Member</h3>
@endsection

@section('content')

    @if(session('errors'))
        <div class="alert alert-danger my-2 mx-2">
            {{ session('errors') }}
        </div>
    @endif

    <form action="{{ route('member.update', $data['member']->id) }}" method="post">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group">
                <label for="kode">Kode</label>
                <input type="text"
                    class="form-control"
                    id="kode"
                    placeholder="Masukan kode"
                    name="kode"
                    value="{{ $data['member']->kode }}">
                @error('kode')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama">Nama</label>
                <input
                    type="text"
                    class="form-control"
                    id="nama"
                    placeholder="Masukan nama"
                    name="nama"
                    value="{{ $data['member']->nama }}">
                @error('nama')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama">Jenis Kelamin</label> <br>
                <input type="radio" name="jenis_kelamin" value="0" {{ $data['member']->jenis_kelamin == 0 ? 'checked' : '' }}> Perempuan
                <input type="radio" name="jenis_kelamin" value="1" {{ $data['member']->jenis_kelamin == 1 ? 'checked' : '' }}> Laki Laki
                @error('jenis_kelamin')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="alamat">Alamat</label>
                <textarea class="form-control" rows="3" placeholder="Masukan alamat" name="alamat">{{ $data['member']->alamat }}</textarea>
                @error('alamat')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Masukan email" name="email" value="{{ $data['member']->user->email }}">
                @error('email')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" placeholder="Masukan password" name="password">
                @error('password')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" name="simpan" class="btn btn-info">Update</button>
        </div>
    </form>


@endsection

resources/views/member/index.blade.php
@extends('template.master')

@section('title', 'Member')

@section('card-title')
    <h3 class="card-title">Member</h3>
@endsection

@push('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.5/datatables.min.css"/>
@endpush

@section('content')

    @if(session('success'))
        <div class="alert alert-success my-2 mx-2">
            {{ session('success') }}
        </div>
    @endif

    <div>
        <a class="btn btn-primary ml-2 my-2" href="{{ route('member.create') }}">Tambah Member</a>
    </div>
    <div class="mx-2">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Kode</th>
                    <th>Nama</th>
                    <th>Jenis Kelamin</th>
                    <th>Alamat</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data['data'] as $key => $item )
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $item->kode }}</td>
                        <td>{{ $item->nama }}</td>
                        <td>{{ $item->jenis_kelamin ? 'Laki-Laki' : "Perempuan" }}</td>
                        <td>{{ $item->alamat }}</td>
                        <td>
                            <form action="/member/{{ $item->id }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <a class="btn btn-info btn-sm" href="/member/{{ $item->id }}">Detail</a>
                                <a class="btn btn-warning btn-sm" href="/member/{{ $item->id }}/edit">Edit</a>
                                <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

@endsection

@push('scripts')
    <script src="{{ asset('/adminlte/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{ asset('/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
    <script>
        $(function () {
            $("#example1").DataTable();
        });
    </script>
@endpush

resources/views/member/show.blade.php
@extends('template.master')

@section('title', 'Member')

@section('card-title')
    <h3 class="card-title">Detail Member</h3>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-2">Nama</div>
        <div class="col-sm">{{ $data['member']->nama }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Kode</div>
        <div class="col-sm">{{ $data['member']->kode }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Email</div>
        <div class="col-sm">{{ $data['member']->user->email }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Alamat</div>
        <div class="col-sm">{{ $data['member']->alamat }}</div>
    </div>
    <div class="row">
        <div class="col-sm-2">Jenis Kelamin</div>
        <div class="col-sm">{{ $data['member']->jenis_kelamin ? "Laki-laki" : "Perempuan" }}</div>
    </div>
@endsection